
name: ${LAB_NAME:?error}--${STUDENT_ID:?error}

services:
# https://fr.wikipedia.org/wiki/Plan%C3%A8te#Plan%C3%A8tes_du_Syst%C3%A8me_solaire


  arts:
    image: debian:pki002
    container_name: ${COMPOSE_PROJECT_NAME}-arts
    hostname: ${COMPOSE_PROJECT_NAME}-ARTS
    volumes:
      - ../../${COMPOSE_PROJECT_NAME}/school:/school
      - ../../${COMPOSE_PROJECT_NAME}/arts/student:/home/student
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "/home/student/lighttpd.sh ; sleep infinity"
    networks:
      school:
        ipv4_address: 10.10.0.0
        aliases:
          - arts.school






  biosciences:
    image: debian:pki002
    container_name: ${COMPOSE_PROJECT_NAME}-biosciences
    hostname: ${COMPOSE_PROJECT_NAME}-BIOSCIENCES
    volumes:
      - ../../${COMPOSE_PROJECT_NAME}/school:/school
      - ../../${COMPOSE_PROJECT_NAME}/biosciences/student:/home/student
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "/home/student/lighttpd.sh ; sleep infinity"
    networks:
      school:
        ipv4_address: 10.20.0.0
        aliases:
          - biosciences.school






  chemistry:
    image: debian:pki002
    container_name: ${COMPOSE_PROJECT_NAME}-chemistry
    hostname: ${COMPOSE_PROJECT_NAME}-CHEMISTRY
    volumes:
      - ../../${COMPOSE_PROJECT_NAME}/school:/school
      - ../../${COMPOSE_PROJECT_NAME}/chemistry/student:/home/student
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "/home/student/lighttpd.sh ; sleep infinity"
    networks:
      school:
        ipv4_address: 10.30.0.0
        aliases:
          - chemistry.school







networks:
  school:
    name: ${COMPOSE_PROJECT_NAME}-school
    ipam:
      config:
        - subnet: 10.0.0.0/8



